version: '3'

services:
  profisco-demo-app:
    build: .
    container_name: profisco-demo-app
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - .:/home/node/app
    depends_on:
      - profisco-demo-db

  profisco-demo-db:
    build: .docker/postgres
    container_name: profisco-demo-db
    restart: on-failure
    tty: true
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
